apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot42danis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: io42danis
  template:
    metadata:
      labels:
        app: io42danis
    spec:
      containers:
      - name: iot42danis
        image: wil42/playground:v1
        ports:
        - containerPort: 8888